- name: Define User Project Name
  set_fact:
    user_project: 'user{{ item }}-project'

- name: Evaluate Camel K Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'camel-k-sub.yml.j2') }}"

- name: Wait for Operator to be Running
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: '{{ user_project }}'
    label_selectors:
      - app = camel-k
      - camel.apache.org/component = operator
      - name = camel-k-operator
    field_selectors:
      - status.phase=Running
  register: r_camelk_operator_pod
  retries: 120
  delay: 10
  until: r_camelk_operator_pod.resources | list | length == 1

- name: Evaluate Camel K View Permission
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'camel-k-rb.yml.j2') }}"
