- name: Define User Project Name
  set_fact:
    user_project: 'user{{ item }}-project'

- name: Evaluate AMQ Broker Operator Group
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'operator-group.yml.j2') }}"

- name: Evaluate AMQ Broker Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'amq_subscription.yml.j2') }}"

- name: Wait for Operator to be Running
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: '{{ user_project }}'
    label_selectors:
      - name = amq-broker-operator
      - rht.comp = Broker_AMQ
    field_selectors:
      - status.phase=Running
  register: r_amq_operator_pod
  retries: 120
  delay: 10
  until: r_amq_operator_pod.resources | list | length == 1
